"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.log_model import LogModel
from basistheory.model.pagination import Pagination
globals()['LogModel'] = LogModel
globals()['Pagination'] = Pagination
from basistheory.model.log_model_paginated_list import LogModelPaginatedList


class TestLogModelPaginatedList(unittest.TestCase):
    """LogModelPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogModelPaginatedList(self):
        """Test LogModelPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LogModelPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
