"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.encryption_key import EncryptionKey


class TestEncryptionKey(unittest.TestCase):
    """EncryptionKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEncryptionKey(self):
        """Test EncryptionKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EncryptionKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
