"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.bank import Bank


class TestBank(unittest.TestCase):
    """Bank unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBank(self):
        """Test Bank"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Bank()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
