"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.bank import Bank
globals()['Bank'] = Bank
from basistheory.model.create_atomic_bank_request import CreateAtomicBankRequest


class TestCreateAtomicBankRequest(unittest.TestCase):
    """CreateAtomicBankRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAtomicBankRequest(self):
        """Test CreateAtomicBankRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateAtomicBankRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
