"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.reactor_formula_model import ReactorFormulaModel
globals()['ReactorFormulaModel'] = ReactorFormulaModel
from basistheory.model.create_reactor_model import CreateReactorModel


class TestCreateReactorModel(unittest.TestCase):
    """CreateReactorModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateReactorModel(self):
        """Test CreateReactorModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateReactorModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
