"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.bank import Bank
globals()['Bank'] = Bank
from basistheory.model.atomic_bank import AtomicBank


class TestAtomicBank(unittest.TestCase):
    """AtomicBank unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAtomicBank(self):
        """Test AtomicBank"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AtomicBank()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
