"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.token_report_model import TokenReportModel
globals()['TokenReportModel'] = TokenReportModel
from basistheory.model.tenant_usage_report_model import TenantUsageReportModel


class TestTenantUsageReportModel(unittest.TestCase):
    """TenantUsageReportModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTenantUsageReportModel(self):
        """Test TenantUsageReportModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TenantUsageReportModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
