"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.encryption_key_model import EncryptionKeyModel


class TestEncryptionKeyModel(unittest.TestCase):
    """EncryptionKeyModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEncryptionKeyModel(self):
        """Test EncryptionKeyModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EncryptionKeyModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
