"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.create_application_model import CreateApplicationModel


class TestCreateApplicationModel(unittest.TestCase):
    """CreateApplicationModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateApplicationModel(self):
        """Test CreateApplicationModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateApplicationModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
