"""
    Basis Theory API

    ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.cursor_pagination import CursorPagination
from basistheory.model.token import Token
globals()['CursorPagination'] = CursorPagination
globals()['Token'] = Token
from basistheory.model.token_cursor_paginated_list import TokenCursorPaginatedList


class TestTokenCursorPaginatedList(unittest.TestCase):
    """TokenCursorPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenCursorPaginatedList(self):
        """Test TokenCursorPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenCursorPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
