"""
    Basis Theory API

    ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.three_ds_authentication import ThreeDSAuthentication
from basistheory.model.three_ds_device_info import ThreeDSDeviceInfo
from basistheory.model.three_ds_method import ThreeDSMethod
from basistheory.model.three_ds_version import ThreeDSVersion
globals()['ThreeDSAuthentication'] = ThreeDSAuthentication
globals()['ThreeDSDeviceInfo'] = ThreeDSDeviceInfo
globals()['ThreeDSMethod'] = ThreeDSMethod
globals()['ThreeDSVersion'] = ThreeDSVersion
from basistheory.model.three_ds_session import ThreeDSSession


class TestThreeDSSession(unittest.TestCase):
    """ThreeDSSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThreeDSSession(self):
        """Test ThreeDSSession"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ThreeDSSession()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
