"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.update_application_model import UpdateApplicationModel


class TestUpdateApplicationModel(unittest.TestCase):
    """UpdateApplicationModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateApplicationModel(self):
        """Test UpdateApplicationModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateApplicationModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
