"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.privacy import Privacy
globals()['Privacy'] = Privacy
from basistheory.model.create_token_response import CreateTokenResponse


class TestCreateTokenResponse(unittest.TestCase):
    """CreateTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTokenResponse(self):
        """Test CreateTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
