"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.basis_theory_error import BasisTheoryError


class TestBasisTheoryError(unittest.TestCase):
    """BasisTheoryError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasisTheoryError(self):
        """Test BasisTheoryError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BasisTheoryError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
