"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.reactor_formula import ReactorFormula
globals()['ReactorFormula'] = ReactorFormula
from basistheory.model.create_reactor_request import CreateReactorRequest


class TestCreateReactorRequest(unittest.TestCase):
    """CreateReactorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateReactorRequest(self):
        """Test CreateReactorRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateReactorRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
