"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.encryption_metadata import EncryptionMetadata
from basistheory.model.privacy import Privacy
globals()['EncryptionMetadata'] = EncryptionMetadata
globals()['Privacy'] = Privacy
from basistheory.model.create_token_request import CreateTokenRequest


class TestCreateTokenRequest(unittest.TestCase):
    """CreateTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTokenRequest(self):
        """Test CreateTokenRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTokenRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
