"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.atomic_bank import AtomicBank
from basistheory.model.pagination import Pagination
globals()['AtomicBank'] = AtomicBank
globals()['Pagination'] = Pagination
from basistheory.model.atomic_bank_paginated_list import AtomicBankPaginatedList


class TestAtomicBankPaginatedList(unittest.TestCase):
    """AtomicBankPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAtomicBankPaginatedList(self):
        """Test AtomicBankPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AtomicBankPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
