"""
    Basis Theory API

    ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.three_ds_cardholder_info import ThreeDSCardholderInfo
from basistheory.model.three_ds_merchant_info import ThreeDSMerchantInfo
from basistheory.model.three_ds_message_extension import ThreeDSMessageExtension
from basistheory.model.three_ds_purchase_info import ThreeDSPurchaseInfo
from basistheory.model.three_ds_requestor_info import ThreeDSRequestorInfo
globals()['ThreeDSCardholderInfo'] = ThreeDSCardholderInfo
globals()['ThreeDSMerchantInfo'] = ThreeDSMerchantInfo
globals()['ThreeDSMessageExtension'] = ThreeDSMessageExtension
globals()['ThreeDSPurchaseInfo'] = ThreeDSPurchaseInfo
globals()['ThreeDSRequestorInfo'] = ThreeDSRequestorInfo
from basistheory.model.authenticate_three_ds_session_request import AuthenticateThreeDSSessionRequest


class TestAuthenticateThreeDSSessionRequest(unittest.TestCase):
    """AuthenticateThreeDSSessionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticateThreeDSSessionRequest(self):
        """Test AuthenticateThreeDSSessionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthenticateThreeDSSessionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
