"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.pagination import Pagination
from basistheory.model.token_model import TokenModel
globals()['Pagination'] = Pagination
globals()['TokenModel'] = TokenModel
from basistheory.model.token_model_paginated_list import TokenModelPaginatedList


class TestTokenModelPaginatedList(unittest.TestCase):
    """TokenModelPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenModelPaginatedList(self):
        """Test TokenModelPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenModelPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
