"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.pagination import Pagination
from basistheory.model.reactor_formula_model import ReactorFormulaModel
globals()['Pagination'] = Pagination
globals()['ReactorFormulaModel'] = ReactorFormulaModel
from basistheory.model.reactor_formula_model_paginated_list import ReactorFormulaModelPaginatedList


class TestReactorFormulaModelPaginatedList(unittest.TestCase):
    """ReactorFormulaModelPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReactorFormulaModelPaginatedList(self):
        """Test ReactorFormulaModelPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReactorFormulaModelPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
