"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.bank_model import BankModel
globals()['BankModel'] = BankModel
from basistheory.model.create_atomic_bank_model import CreateAtomicBankModel


class TestCreateAtomicBankModel(unittest.TestCase):
    """CreateAtomicBankModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAtomicBankModel(self):
        """Test CreateAtomicBankModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateAtomicBankModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
