"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.application_model import ApplicationModel
from basistheory.model.pagination import Pagination
globals()['ApplicationModel'] = ApplicationModel
globals()['Pagination'] = Pagination
from basistheory.model.application_model_paginated_list import ApplicationModelPaginatedList


class TestApplicationModelPaginatedList(unittest.TestCase):
    """ApplicationModelPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationModelPaginatedList(self):
        """Test ApplicationModelPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationModelPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
