"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.log import Log
from basistheory.model.pagination import Pagination
globals()['Log'] = Log
globals()['Pagination'] = Pagination
from basistheory.model.log_paginated_list import LogPaginatedList


class TestLogPaginatedList(unittest.TestCase):
    """LogPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogPaginatedList(self):
        """Test LogPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LogPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
