"""
    Basis Theory API

    ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.bin_details_bank import BinDetailsBank
from basistheory.model.bin_details_country import BinDetailsCountry
from basistheory.model.bin_details_product import BinDetailsProduct
globals()['BinDetailsBank'] = BinDetailsBank
globals()['BinDetailsCountry'] = BinDetailsCountry
globals()['BinDetailsProduct'] = BinDetailsProduct
from basistheory.model.bin_details import BinDetails


class TestBinDetails(unittest.TestCase):
    """BinDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBinDetails(self):
        """Test BinDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BinDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
