"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.card_model import CardModel


class TestCardModel(unittest.TestCase):
    """CardModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCardModel(self):
        """Test CardModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CardModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
