"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.reactor_formula_model import ReactorFormulaModel
globals()['ReactorFormulaModel'] = ReactorFormulaModel
from basistheory.model.reactor_model import ReactorModel


class TestReactorModel(unittest.TestCase):
    """ReactorModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReactorModel(self):
        """Test ReactorModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReactorModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
