"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.reactor_formula_configuration_model import ReactorFormulaConfigurationModel
from basistheory.model.reactor_formula_request_parameter_model import ReactorFormulaRequestParameterModel
globals()['ReactorFormulaConfigurationModel'] = ReactorFormulaConfigurationModel
globals()['ReactorFormulaRequestParameterModel'] = ReactorFormulaRequestParameterModel
from basistheory.model.create_reactor_formula_model import CreateReactorFormulaModel


class TestCreateReactorFormulaModel(unittest.TestCase):
    """CreateReactorFormulaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateReactorFormulaModel(self):
        """Test CreateReactorFormulaModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateReactorFormulaModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
