"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import basistheory
from basistheory.api.tokenize_api import TokenizeApi  # noqa: E501


class TestTokenizeApi(unittest.TestCase):
    """TokenizeApi unit test stubs"""

    def setUp(self):
        self.api = TokenizeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tokenize(self):
        """Test case for tokenize

        """
        pass


if __name__ == '__main__':
    unittest.main()
