"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.card_model import CardModel
globals()['CardModel'] = CardModel
from basistheory.model.atomic_card_model import AtomicCardModel


class TestAtomicCardModel(unittest.TestCase):
    """AtomicCardModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAtomicCardModel(self):
        """Test AtomicCardModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AtomicCardModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
