"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.atomic_card_model import AtomicCardModel
from basistheory.model.pagination import Pagination
globals()['AtomicCardModel'] = AtomicCardModel
globals()['Pagination'] = Pagination
from basistheory.model.atomic_card_model_paginated_list import AtomicCardModelPaginatedList


class TestAtomicCardModelPaginatedList(unittest.TestCase):
    """AtomicCardModelPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAtomicCardModelPaginatedList(self):
        """Test AtomicCardModelPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AtomicCardModelPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
