"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.atomic_card import AtomicCard
from basistheory.model.pagination import Pagination
globals()['AtomicCard'] = AtomicCard
globals()['Pagination'] = Pagination
from basistheory.model.atomic_card_paginated_list import AtomicCardPaginatedList


class TestAtomicCardPaginatedList(unittest.TestCase):
    """AtomicCardPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAtomicCardPaginatedList(self):
        """Test AtomicCardPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AtomicCardPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
