"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.pagination import Pagination
from basistheory.model.reactor import Reactor
globals()['Pagination'] = Pagination
globals()['Reactor'] = Reactor
from basistheory.model.reactor_paginated_list import ReactorPaginatedList


class TestReactorPaginatedList(unittest.TestCase):
    """ReactorPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReactorPaginatedList(self):
        """Test ReactorPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReactorPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
