"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.card import Card
globals()['Card'] = Card
from basistheory.model.create_atomic_card_request import CreateAtomicCardRequest


class TestCreateAtomicCardRequest(unittest.TestCase):
    """CreateAtomicCardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAtomicCardRequest(self):
        """Test CreateAtomicCardRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateAtomicCardRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
