"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.encryption_key_model import EncryptionKeyModel
globals()['EncryptionKeyModel'] = EncryptionKeyModel
from basistheory.model.encryption_metadata_model import EncryptionMetadataModel


class TestEncryptionMetadataModel(unittest.TestCase):
    """EncryptionMetadataModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEncryptionMetadataModel(self):
        """Test EncryptionMetadataModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EncryptionMetadataModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
