"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.react_request import ReactRequest


class TestReactRequest(unittest.TestCase):
    """ReactRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReactRequest(self):
        """Test ReactRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReactRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
