"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.update_reactor_request import UpdateReactorRequest


class TestUpdateReactorRequest(unittest.TestCase):
    """UpdateReactorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateReactorRequest(self):
        """Test UpdateReactorRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateReactorRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
