"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.card import Card
globals()['Card'] = Card
from basistheory.model.update_atomic_card_request import UpdateAtomicCardRequest


class TestUpdateAtomicCardRequest(unittest.TestCase):
    """UpdateAtomicCardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateAtomicCardRequest(self):
        """Test UpdateAtomicCardRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateAtomicCardRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
