"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.encryption_metadata_model import EncryptionMetadataModel
from basistheory.model.privacy_model import PrivacyModel
globals()['EncryptionMetadataModel'] = EncryptionMetadataModel
globals()['PrivacyModel'] = PrivacyModel
from basistheory.model.token_model import TokenModel


class TestTokenModel(unittest.TestCase):
    """TokenModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenModel(self):
        """Test TokenModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
