"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.atomic_bank_model import AtomicBankModel
from basistheory.model.pagination import Pagination
globals()['AtomicBankModel'] = AtomicBankModel
globals()['Pagination'] = Pagination
from basistheory.model.atomic_bank_model_paginated_list import AtomicBankModelPaginatedList


class TestAtomicBankModelPaginatedList(unittest.TestCase):
    """AtomicBankModelPaginatedList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAtomicBankModelPaginatedList(self):
        """Test AtomicBankModelPaginatedList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AtomicBankModelPaginatedList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
