"""
    Basis Theory API

    ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import basistheory
from basistheory.api.application_templates_api import ApplicationTemplatesApi  # noqa: E501


class TestApplicationTemplatesApi(unittest.TestCase):
    """ApplicationTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get(self):
        """Test case for get

        """
        pass

    def test_get_by_id(self):
        """Test case for get_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
