"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.pagination import Pagination
from basistheory.model.token import Token
globals()['Pagination'] = Pagination
globals()['Token'] = Token
from basistheory.model.paginated_token_list import PaginatedTokenList


class TestPaginatedTokenList(unittest.TestCase):
    """PaginatedTokenList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedTokenList(self):
        """Test PaginatedTokenList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedTokenList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
