"""
    BasisTheory Vault API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import basistheory
from basistheory.model.token_metrics import TokenMetrics
globals()['TokenMetrics'] = TokenMetrics
from basistheory.model.token_report_model import TokenReportModel


class TestTokenReportModel(unittest.TestCase):
    """TokenReportModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenReportModel(self):
        """Test TokenReportModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenReportModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
